// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRC3lPlFxB1BsCFU4zAwAA3CxrpyJUpYs',
    appId: '1:960114528232:web:3f3b3ba36eb4e133185e5d',
    messagingSenderId: '960114528232',
    projectId: 'collectorscenter-fbfdc',
    authDomain: 'collectorscenter-fbfdc.firebaseapp.com',
    storageBucket: 'collectorscenter-fbfdc.appspot.com',
    measurementId: 'G-4ML2G5XGQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPiTzUxsL4mexAyxGF__ymh7ovBro4IpA',
    appId: '1:960114528232:android:24c56f22c0ef1c3f185e5d',
    messagingSenderId: '960114528232',
    projectId: 'collectorscenter-fbfdc',
    storageBucket: 'collectorscenter-fbfdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZWqYP5Opj1oNC4GBYR-xpRj4uU15kgE',
    appId: '1:960114528232:ios:b1d5d05df8f4168c185e5d',
    messagingSenderId: '960114528232',
    projectId: 'collectorscenter-fbfdc',
    storageBucket: 'collectorscenter-fbfdc.appspot.com',
    iosBundleId: 'com.example.collectorsCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANZWqYP5Opj1oNC4GBYR-xpRj4uU15kgE',
    appId: '1:960114528232:ios:70eae32232fa39e6185e5d',
    messagingSenderId: '960114528232',
    projectId: 'collectorscenter-fbfdc',
    storageBucket: 'collectorscenter-fbfdc.appspot.com',
    iosBundleId: 'com.example.collectorsCenter.RunnerTests',
  );
}
