// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ5j0DMcPwOl7MZEFeqzmoR06g1VnV3so',
    appId: '1:1052709621623:web:3acb9aca8012902fd59b72',
    messagingSenderId: '1052709621623',
    projectId: 'collectioncenter-c9abe',
    authDomain: 'collectioncenter-c9abe.firebaseapp.com',
    storageBucket: 'collectioncenter-c9abe.appspot.com',
    measurementId: 'G-D9E3SPQN20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIPcMGfEGkJKL_1IW9QJ9W2K0jTIivuuM',
    appId: '1:1052709621623:android:d8d044e2d96b1118d59b72',
    messagingSenderId: '1052709621623',
    projectId: 'collectioncenter-c9abe',
    storageBucket: 'collectioncenter-c9abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_K_Dj8oXL5ATjFymuZejp9vuZbKCrngc',
    appId: '1:1052709621623:ios:f6753bebe10886bad59b72',
    messagingSenderId: '1052709621623',
    projectId: 'collectioncenter-c9abe',
    storageBucket: 'collectioncenter-c9abe.appspot.com',
    iosBundleId: 'com.example.collectorsCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_K_Dj8oXL5ATjFymuZejp9vuZbKCrngc',
    appId: '1:1052709621623:ios:57627a2064bd0d8ed59b72',
    messagingSenderId: '1052709621623',
    projectId: 'collectioncenter-c9abe',
    storageBucket: 'collectioncenter-c9abe.appspot.com',
    iosBundleId: 'com.example.collectorsCenter.RunnerTests',
  );
}
